//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payslip_adjustment
    {
        public long id { get; set; }
        public Nullable<long> payslip_id { get; set; }
        public string type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string adjustment { get; set; }
        public string status { get; set; }
    }
}
