//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_government
    {
        public long id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<bool> has_sss { get; set; }
        public string sss_number { get; set; }
        public Nullable<bool> has_philhealth { get; set; }
        public string philhealth_number { get; set; }
        public Nullable<bool> has_pagibig { get; set; }
        public string pagibig_number { get; set; }
    }
}
