//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_timesheet
    {
        public long id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<decimal> working_days { get; set; }
        public Nullable<decimal> holidays { get; set; }
        public Nullable<decimal> days_absent { get; set; }
        public Nullable<decimal> duty_hours { get; set; }
        public Nullable<decimal> lates { get; set; }
        public Nullable<decimal> undertime { get; set; }
        public Nullable<decimal> overtime { get; set; }
        public Nullable<long> preparedby { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<long> approvedby { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public Nullable<long> cancelledby { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public string status { get; set; }
    }
}
