//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loan
    {
        public long id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string status { get; set; }
        public Nullable<long> preparedby { get; set; }
        public Nullable<System.DateTime> dateprepared { get; set; }
        public Nullable<long> releasedby { get; set; }
        public Nullable<System.DateTime> datereleased { get; set; }
        public Nullable<long> voidby { get; set; }
        public Nullable<System.DateTime> datevoid { get; set; }
    }
}
