//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payslip
    {
        public long id { get; set; }
        public Nullable<long> timesheet_id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> semi_monthly_rate { get; set; }
        public Nullable<long> preparedby { get; set; }
        public Nullable<System.DateTime> dateprepared { get; set; }
        public Nullable<long> approvedby { get; set; }
        public Nullable<System.DateTime> dateapproved { get; set; }
        public Nullable<long> cancelledby { get; set; }
        public Nullable<System.DateTime> datecancelled { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> datefrom { get; set; }
        public Nullable<System.DateTime> dateto { get; set; }
    }
}
