//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_schedule
    {
        public long id { get; set; }
        public Nullable<System.DateTime> time_in { get; set; }
        public Nullable<System.DateTime> time_out { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> grace_time { get; set; }
    }
}
