//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_employee_list_v2
    {
        public long EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string CompanyName { get; set; }
        public string DepartmentName { get; set; }
        public string Job { get; set; }
    }
}
