//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollSystem.Model.dbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Employee
    {
        public long id { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string status { get; set; }
        public Nullable<long> company { get; set; }
        public Nullable<long> department { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string civil_status { get; set; }
        public string gender { get; set; }
        public string usertype { get; set; }
        public string CivilStatus { get; set; }
        public string EmployeeName { get; set; }
        public string Company_Name { get; set; }
        public string Department_Name { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> DeptId { get; set; }
        public string Employee_Status { get; set; }
        public string email { get; set; }
        public Nullable<long> schedule { get; set; }
        public Nullable<long> job_id { get; set; }
        public string JobName { get; set; }
    }
}
